### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by OrangoMango** [mikhio/Tkinter-games#1]
Nice game

**Comment by mikhio** [comment]
> Nice game

It's sarcasm?

**Comment by OrangoMango** [comment]
No

**Comment by OrangoMango** [comment]
Why?

**Comment by OrangoMango** [comment]
Follow me please 🥺
Thanks

**Comment by mikhio** [comment]
> Why?

Because my "game" is not good and also it didn't finish

**Comment by OrangoMango** [comment]
Yes, I looked only the code, and it look good. 🤗

**Comment by OrangoMango** [comment]
I have invited you to my organisation:
https://github.com/Python3Games

**Comment by mikhio** [comment]
> I have invited you to my organisation:
> https://github.com/Python3Games

Sorry but I can't join your group

**Comment by OrangoMango** [comment]
Why?
Can u follow me?

**Comment by mikhio** [comment]
Because opportunities of the owner are not comfortable for me

**Comment by OrangoMango** [comment]
Ok, but can u follow me. Please🥺🥺🥺

**Comment by mikhio** [comment]
Ok

**Comment by OrangoMango** [comment]
Thank you very much, if you want, you can make an organisation and I'm the
member and you are the owner.
Then you can invite me.

**Comment by OrangoMango** [comment]
Anyway thank you
